### ISSUE TITLE
Par mensich chybek + doporuceni?

### ISSUE THREAD

**Issue by JamesTheCode** [Salamek/czech-post-api#1]
Ahoj,

vsiml jsem si par mensich chyb:

v readme.md je misto Ceska posta api napsane ppl myapi, coz trochu mate.

V `FakeClient.php` na line 240 je: `@mail('adam.schubert@sg1-game.net', $importName, file_get_contents($tmpfname));` Toho jsem si vsiml nahodou.

Ja si hodne vazim, ze se nasel nekdo kdo udelal volne pristupne napojeni na postu, tak aby to i ostatni mohli pouzivat.

**Comment by Salamek** [comment]
@JamesTheCode Ahoj, opraveno, ten mail je zapomenuty debug, odstraneno...
Ppozdeji planuji pridat i offic Cert API
