### ISSUE TITLE
senderTypePackageIdFormat jen pro SenderType::C a B ?

### ISSUE THREAD

**Issue by progresak** [Salamek/czech-post-api#2]
Ahoj, 
skvělá knihovna, funguje velmi pěkně, narazil jsem jen na menší zádrhel.
Na řádce 15 v Tools.php
```
    /** @var array  */
    public static $senderTypePackageIdFormat = [
        SenderType::C => '%s%04d%05d%s%s',
        SenderType::B => '%s%04d%05d%s%s',
    ];
```
jsou formáty pro typy podavatele.

V případě, že je podavatel jiného typu (v našem případě SenderType::L), script spadne na řádce Tools::73. 

Z jakého důvodu tam nejsou všechny typy? Je možné přidat formáty pro všechny SenderType ? :) 
```
   SenderType::M => '%s%05d%04d%s%s',
   SenderType::L => '%s%05d%04d%s%s',
   ...
```

**Comment by Salamek** [comment]
@progresak ahoj, pokud zjistis formaty pro vsechny typy tak je s radosti pridam
