### ISSUE TITLE
Problem s dokumentaci

### ISSUE THREAD

**Issue by JamesTheCode** [Salamek/czech-post-api#3]
Ahoj,
promin, ale nevim kam se obratit na dotaz ohledne fungovani api ceske posty.

1. k tvemu reseni potrebuju jen zakladni prihlasovaci udaje a myPackageIdFromNumberSeries?
MyPackageIdFromNumberSeries to nam asi prideli ceska posta(obchodni zastupce)?

2. Potrebuju k tomu jeste nejake jine udaje, treba podobne jako ppl id depa, nebo treba technologicke cislo?

Nerad takhle obtezuji, ale opravdu se nemam na koho jineho obratit.

Dekuju moc.

**Comment by Salamek** [comment]
Ahoj, tato knihovna pouziva neoficialni postup pro nahravani dat na ceskou postu, parsuje a POSTtuje data na Podani Online, proto jsou potreba jen pristupy na podani online a senderId.

1. series id je cislo baliku bez prefixu a suffixu okolo tzn pro DR9569235683C je to 235683, je to cislo co se iteruje +1 atp.

2. Potrebujes jeste nastavit senderId, je to prvni parameter pro Sender('C9569', ...);

V pohode se ptej, me to nevadi :) 

Jinak nekde jsem cetl ze mas certifikat pro pristup k oficialnimu API ceske posty ? Jak jsi jej vygeneroval ? Ja nikde nemuzu najit doc jak se k tomu certu dostat bez toho abych lezl na czech point...

Planuji totiz udelat knihovnu k offic API, ale bez certu to nedam.

**Comment by JamesTheCode** [comment]
Diky moc. 

Musel jsem zase podobne jako na ppl prestylovat label aby se nam vesel na termotiskarnu Zebra - v linuxu(CUPS) mi neslo A4 vytisknout spravne. Nakonec jsem to prekodoval na format B6 :D. 

To je otazka jestli bys nemel zajem to do knihovny pridat, jde o to ze oni dodavaji stitky v urcite velikosti a pokud k tiskarne nemas software(u zebry nesel na linuxu), tak to tam asi nevejde.

Celkem usmevne u ppl bylo ze muj stitek jim nekolikrat zastavil linku tak byli celkem nastvani, i kdyz ten stitek byl schvalen jejich technikem, stacilo ale pridat znacne mezery ze vsech stran caroveho kodu a jelo to v poho. 

Jen tak pro info, u stitku u posty nam obchodak rekl ze pozaduji aby barcode mel min. rozmer 40x45, jinak ho neschvali, pritom jejich oficialni stitky, i tvuj stitek, maji ocividne barcode o dost mensi a asi to je v pohode.

Tak certifikat jsme museli vyzvednout na prave na czechpointu a jinak to asi nejde.

1. Zazadas o nej pres postsignum applikaci. (osobni komercni byl nas pripad)

2. Na czech pointu ti ho nahrajou na flashku. - stoji to par stovek a musi se kazdy rok obnovovat.

3. Musis ho nainstalovat z toho sameho pocitace, z ktereho si o nej zadal.

4. dostanes klice, s kteryma pak da pracovat v administraci podanionline, presneji Sprava koncovych uzivatelu.


Mimochodem to ze potrebujes certifikat, abys jim na api mohl posilat data mi prijde zbytecne a celkem dost otravne, hlavne kdyz hraji na to ze postsignum je certifikacni autorita ale jejich https certifikat mi v mnoha prohlizecich vyhodi chybu a musim pridat vyjimku....

Pokud mas zajem ted jsem ten certifikat resil krok po kroku, tak jsem schopny poradit vice.

**Comment by JamesTheCode** [comment]
Uz mi to jede super! Diky moc.

Jenom jeste info

to senderId jsem zjistil ze musi byt bez pismena, to tam pak dodavas podle typy odesilatele.

Plus jeste to cislo ktere se iteruje, v tvem prikladu 235683 - musi byt petimistne ne sestimistne, za to se pak jeste dodava asi kontrolni cislo plus typ odesilatele.

Jeste me trosku zmatlo, kdyz jsem zjistil, ze to automaticky uzavira vsechny predesle podani a maze to prazdne.

Jeste je mozna trochu skoda ze to dokaze vytvorit jen 1 podani hodinu, tak jak ted mas vytvoreny $filingDate a $filingId.

Jinak je to super a usetril si nam hodne casu.

Diky.
