### ISSUE TITLE
API údaje 

### ISSUE THREAD

**Issue by TechOverflow** [Salamek/czech-post-api#6]
Zdarec! Možná blbej dotaz ale nikde v ofic. dokumentacích ČP se nedá dočíst kde zjistit uživatelské jméno a heslo pro API. Předpokládám, že smlouva je podmínkou, ale nikde v zákaznické aplikaci jsem údaje neviděl. Musí se tedy komunikovat s obchoďákem?

**Comment by Salamek** [comment]
@TechOverflow Ahoj, tohle je neoficialni API knihovna ktera pouziva Podani Online aplikaci.
Tzn ze se prihlasi jako uzivatel, parsuje HTML a dela POST/GET requesty jako uzivatel... pouziva CSV import informaci o balicich... Takze tato knihovna pouziva prihlasovaci udaje k Podani Online.

Slysel jsem nejake zvesti ze existuje i officialni OPRAVDOVE API ceske posty ale v dobe kdy jsem to resil to bylo neco jako krev jednorozce... pokud k tomu mas nejakou dokumentaci etc, rad bych ji videl (rad bych to pridal do teto knihovny jako hlavni moznost predavani dat a puvodni reseni nechat jako legacy stuff)

**Comment by Salamek** [comment]
@TechOverflow BTW tahle knihovna ma podobne API jako https://github.com/Salamek/PplMyApi coz je knihovna pouzivajici officialni API PPL... kdyby jsi chtel implementovat PPL prepravce

**Comment by TechOverflow** [comment]
Tušil sem to, pak jsem našel ve FakeClientovi že to jede přes login. Je to pochopitelný, ČP prostě nemůže udělat klasický API a donedávna tracking se musel externě řešit scrapingem. Obchoďáka sem se na to "ofic API" ptal minulej rok ale dostal sem jen vyhýbavý odpovědi.

Tak díky za info, vyzkouším to.
