### ISSUE TITLE
Balíkovna

### ISSUE THREAD

**Issue by TechOverflow** [Salamek/czech-post-api#7]
Zdarec, 

bylo by reálné přes tuto api podávat balíky na Balíkovnu? 
Popř. co by bylo nutné změnit?

Díky

**Comment by TechOverflow** [comment]
Dodatek: 
Jestli to chápu správně, rozdíl je především ve štítkách.
Balíkovna funguje se zvláštní adresou ve formátu
```
Jméno Přijmení
BALÍKOVNA
12000 Praha - Příklad
```
a tedy podání jako takový by se nemělo lišit, akorát je tedy potřeba přidat další typ štítku?

**Comment by Salamek** [comment]
@TechOverflow Pokud import dat do Podani Online probiha stejne i pro "Balikovnu" Tak staci pridat dalsi typ stitku, pravdepodobne zkopirovat cely Label.php na napr. LabelBalikovna.php a tam se vyradit...

**Comment by TechOverflow** [comment]
Díky
